name: omero_devs
channels:
  - conda-forge
dependencies:
  - python=3.8.15
  - pip=23.2.1
  - zeroc-ice=3.6.5
  - pip:
    - setuptools==65.4.1
    - ezomero==1.2.1
    - jupyterlab==4.0.5
    - ome-zarr==0.8.0
    - omero-cli-zarr==0.5.3
