name: omero_devs
channels:
  - conda-forge
dependencies:
  - zeroc-ice=3.6.5
  - pip
  - python
  - pip:
    - ezomero==3.1.0
    - jupyterlab==4.2.5
    - matplotlib==3.9.2
    - ome-zarr==0.9.0
    - omero-cli-zarr==0.5.5
