name: omero_devs
channels:
  - ome
  - defaults
dependencies:
  - pip=20.3
  - omero-py=5.8.2
  - zeroc-ice36-python=3.6.5
  - pip:
    - ezomero==0.1.0
    - ome-zarr==0.0.17
    - omero-cli-zarr==0.0.9
    - zarr==2.6.1
