name: omero_devs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - pip=22.2.2
  - zeroc-ice=3.6.5
  - omero-py=5.12.0
  - matplotlib=3.6.0
  - notebook=6.4.12
  - pip:
    - setuptools==65.4.1
    - numpy==1.23.3
    - ezomero==1.1.1
    - ome-zarr==0.6.0
    - omero-cli-zarr==0.5.0
    - zarr==2.13.2