name: omero_devs
channels:
  - ome
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - cffi=1.14.4
  - chardet=3.0.4
  - cryptography=3.2.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - freetype=2.10.4
  - future=0.18.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - omero-py=5.8.2
  - openssl=1.1.1h
  - packaging=20.7
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.2
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.12
  - python-dateutil=2.8.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - readline=8.0
  - requests=2.25.0
  - send2trash=1.5.0
  - setuptools=50.3.2
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=4.3.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeroc-ice36-python=3.6.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - alabaster==0.7.12
    - babel==2.9.0
    - cachey==0.2.1
    - cycler==0.10.0
    - dask==2.30.0
    - docutils==0.16
    - freetype-py==2.2.0
    - heapdict==1.0.1
    - imageio==2.9.0
    - imagesize==1.2.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.3
    - napari==0.3.8
    - napari-plugin-engine==0.1.8
    - napari-svg==0.1.4
    - numpydoc==1.1.0
    - psutil==5.7.3
    - pyopengl==3.1.5
    - pytz==2020.4
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - scipy==1.5.4
    - snowballstemmer==2.0.0
    - sphinx==3.3.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - tifffile==2020.9.3
    - toolz==0.11.1
    - typing-extensions==3.7.4.3
    - vispy==0.6.6
    - wrapt==1.12.1
    - ezomero==0.0.3
